Main code smell one line issue
PANTHEONtech/lighty-yang-validator pull request #19
Opened 2021-02-24 14:53 UTC by PeterSuna

- Add parametrized type to generic
- Merge this if statement with the enclosing one
- Define a constant instead of duplicating this litera
- Remove deprecated class DeclaredEffectiveStatementBase
   Used AbstractDeclaredEffectiveStatement and its subclasses instead
- Use only SLF4J_SIGN_ONLY_FORMAT supress warning with
   justification and only on required methods.
- Use Collections.emptyList() insed of constat.
- Fix retun generic collection from declaredSubstatements().

2021-02-25 14:14 UTC, vainyksi requested changes
minor changes

2021-02-25 14:14 UTC, vainyksi commented on src/main/java/io/lighty/yang/validator/simplify/stream/TrackingXmlParserStream.java
> +        final TypeAwareCodec<?,NamespaceContext,?> xmlCodec = codecs.codecFor((TypedDataSchemaNode) node);
formatting
`TypeAwareCodec<?, NamespaceContext, ?>`

2021-02-26 07:41 UTC, PeterSuna commented on src/main/java/io/lighty/yang/validator/formats/yang/printer/ModulePrinter.java
> +    private static final String REFERENCE = "reference";
done

2021-02-26 07:42 UTC, PeterSuna commented on src/main/java/io/lighty/yang/validator/simplify/stream/TrackingXmlParserStream.java
> +        final TypeAwareCodec<?,NamespaceContext,?> xmlCodec = codecs.codecFor((TypedDataSchemaNode) node);
done

2021-02-26 09:26 UTC, vainyksi approved these changes

2021-02-26 12:19 UTC, vainyksi approved these changes

2021-02-26 12:19 UTC, merged