Remove usage of EffectiveSchemaContext class
PANTHEONtech/lighty-yang-validator pull request #30
Opened 2021-03-04 15:06 UTC by PeterSuna

- EffectiveSchemaContext is declared with
   VisibleForTesting annotation.

Signed-off-by: Peter Suna <peter.suna@pantheon.tech>

2021-03-04 15:47 UTC, vainyksi requested changes

2021-03-04 15:47 UTC, vainyksi commented on src/main/java/io/lighty/yang/validator/formats/Analyzer.java
> +    private void fillDeclaredStatements(final Set<DeclaredStatement<?>> resultStatements,
rework this to not use output parameter ... rather return the result

2021-03-04 15:47 UTC, vainyksi commented on src/main/java/io/lighty/yang/validator/formats/Analyzer.java
> +                fillDeclaredStatements(resultStatements, submodules);
after output param will be removed, you can recursively addAll(fillDeclaredStatements())

2021-03-04 16:03 UTC, vainyksi approved these changes

2021-03-08 09:59 UTC, miroslavKovacPantheon approved these changes

2021-03-08 11:41 UTC, merged